name: Update dependencies

on:
  ? workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get install -y libpcsclite-dev
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v7.0.1
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # pin@stable
        with:
          toolchain: stable
      - run: cargo install cargo-edit cargo-audit
      - run: cd emvpt && cargo upgrade && cargo update && cargo test
      - run: cd terminalsimulator && cargo upgrade && cargo update && cargo test
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # pin@v8.1.1
        with:
          title: Update dependencies
          commit-message: Update dependencies
          delete-branch: true
      # Not all cargo audit findings can be fixed, hence create PR first
      - run: cd emvpt && cargo audit
      - run: cd terminalsimulator && cargo audit
